services:
  app:
    container_name: shortener-app
    build:
      context: .
      dockerfile: Dockerfile
    image: shortener-app:latest
    ports:
      - "9999:9999"
    environment:
       - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database
    networks:
      - shortener-network

  database:
    container_name: shortener-db
    image: postgres:17
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=4602'
      - 'POSTGRES_DB=url_shortener'
    ports:
      - "5432:5432"
    networks:
      - shortener-network

networks:
  shortener-network:
    driver: bridge
